
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale                   : "en-US"
title                    : "Aditya Sagar"
title_separator          : "-"
name                     : "Aditya Sagar"
description              : "Ahm, I mean me"
url                      : https://aditya-sagar.com
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : karx/homepage
teaser                   : "/assets/images/Teaser.png"
logo                     : "/assets/images/Teaser.png" # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  staticman:
  allowedFields          : # ['name', 'email', 'url', 'message']
  branch                 : # "master"
  commitMessage          : # "New comment by {fields.name}"
  filename               : # comment-{@timestamp}
  format                 : # "yml"
  moderation             : # true
  path                   : # "/_data/comments/{options.slug}" (default)
  requiredFields         : # ['name', 'email', 'message']
  transforms:
    email                : # "md5"
  generatedFields:
    date:
      type               : # "date"
      options:
        format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
  endpoint               : # URL of your own deployment with trailing slash, will fallback to the public instance
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # 011494950284887480085:2jtg_invzz0
  instant_search         : # false (default), true
# SEO Related
google_site_verification : SfADch199waQtRPBHttWkqIotuDYsX0txgLtfKCoPXs
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               : thereforlaughs

linkedin                 : aditya-sagar-6762aba4/
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles


# Analytics
analytics:
  provider               : "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : UA-125563076-1
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Aditya Sagar"
  avatar           : "/assets/images/AdityaSagar-New.jpg"
  bio              : "Ahm, I mean me"
  location         : "India"
  email            : aditya.sagar.official@gmail.com
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:aditya.sagar.official@gmail.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://aditya-sagar.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/thereforlaughs"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/karx"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.linkedin.com/in/aditya-sagar-6762aba4/"

# Site Footer
footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://aditya-sagar.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/thereforlaughs"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/karx"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.linkedin.com/in/aditya-sagar-6762aba4/"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


collections:
  projects:
     output: true
     permalink: /:collection/:path
     layout: projecto
  travel:
     output: true
     permalink: /:collection/:path
     layout: single
  books:
     output: true
     permalink: /:collection/:path
     layout: single



# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
# timezone: Asia/Calcutta


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      toc: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: false
      toc: false
  # _travel
  - scope:
      path: ""
      type: travel
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      toc: false
  # _books
  - scope:
      path: ""
      type: book
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      toc: false



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"


## Javascript
head_scripts:
  - path: https://unpkg.com/@google/model-viewer@0.8.1/dist/model-viewer.js
    is_module: true
  - path: https://unpkg.com/@google-web-components/google-chart@3.0.0/google-chart.js?module
    is_module: true